Address actionlint issues in weekly-pulumi-update.yml

diff --git a/.github/workflows/weekly-pulumi-update.yml b/.github/workflows/weekly-pulumi-update.yml
--- a/.github/workflows/weekly-pulumi-update.yml
+++ b/.github/workflows/weekly-pulumi-update.yml
@@ -49,38 +49,45 @@ jobs:
           github_token: ${{ steps.app-auth.outputs.token }}
       - name: Update Pulumi/Pulumi
         id: gomod
-        run: >-
+        run: |
           git config --local user.email 'bot@pulumi.com'
           git config --local user.name 'pulumi-bot'
-          git checkout -b update-pulumi/${{ github.run_id }}-${{ github.run_number }}
+          git checkout -b "update-pulumi/${{ github.run_id }}-${{ github.run_number }}"
           gh repo view pulumi/pulumi --json latestRelease --jq .latestRelease.tagName | sed 's/^v//' > .pulumi.version
-          VERSION=$(cat .pulumi.version) find . -name go.mod
-          -execdir sh -c 'go get github.com/pulumi/pulumi/pkg/v3@v${VERSION}
-          github.com/pulumi/pulumi/sdk/v3@v${VERSION}; go mod tidy' \;
+          VERSION=$(cat .pulumi.version)
+          find . -name go.mod -execdir sh -c \
+            "go get github.com/pulumi/pulumi/pkg/v3@v${VERSION} \
+            github.com/pulumi/pulumi/sdk/v3@v${VERSION}; go mod tidy" \;
           git update-index -q --refresh
-          if ! git diff-files --quiet; then echo changes=1 >> "$GITHUB_OUTPUT"; fi
+          if ! git diff-files --quiet; then
+            echo "changes=1" >> "$GITHUB_OUTPUT"
+          fi
       - name: Provider with Pulumi Upgrade
         if: steps.gomod.outputs.changes != 0
-        run: >-
+        run: |
           make codegen && make local_generate
           git add sdk/nodejs
-          git commit -m "Regenerating Node.js SDK based on updated modules"
-          || echo "ignore commit failure, may be empty"
+          git commit -m "Regenerating Node.js SDK based on updated modules" \
+            || echo "ignore commit failure, may be empty"
           git add sdk/python
-          git commit -m "Regenerating Python SDK based on updated modules" || echo "ignore commit failure, may be empty"
+          git commit -m "Regenerating Python SDK based on updated modules" \
+            || echo "ignore commit failure, may be empty"
           git add sdk/dotnet
-          git commit -m "Regenerating .NET SDK based on updated modules" || echo "ignore commit failure, may be empty"
+          git commit -m "Regenerating .NET SDK based on updated modules" \
+            || echo "ignore commit failure, may be empty"
           git add sdk/go*
-          git commit -m "Regenerating Go SDK based on updated modules" || echo "ignore commit failure, may be empty"
+          git commit -m "Regenerating Go SDK based on updated modules" \
+            || echo "ignore commit failure, may be empty"
           git add sdk/java*
-          git commit -m "Regenerating Java SDK based on updated modules" || echo "ignore commit failure, may be empty"
+          git commit -m "Regenerating Java SDK based on updated modules" \
+            || echo "ignore commit failure, may be empty"
           git add .
           git commit -m "Updated modules" || echo "ignore commit failure, may be empty"
-          git push origin update-pulumi/${{ github.run_id }}-${{ github.run_number }}
+          git push origin "update-pulumi/${{ github.run_id }}-${{ github.run_number }}"
       - name: Create PR
         id: create-pr
         if: steps.gomod.outputs.changes != 0
-        run: >
+        run: |
           ver=$(cat .pulumi.version)
           msg="Automated upgrade: bump pulumi/pulumi to ${ver}"
           gh pr create -t "$msg" -b "$msg"
